# Generated by Django 4.2.7 on 2025-07-27 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('default_video_quality', models.CharField(choices=[('low', 'Low (360p)'), ('medium', 'Medium (720p)'), ('high', 'High (1080p)'), ('ultra', 'Ultra (4K)')], default='medium', max_length=20)),
                ('default_audio_quality', models.CharField(choices=[('low', 'Low (32kbps)'), ('medium', 'Medium (64kbps)'), ('high', 'High (128kbps)'), ('ultra', 'Ultra (256kbps)')], default='medium', max_length=20)),
                ('adaptive_quality', models.BooleanField(default=True)),
                ('data_saver_mode', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
