# Generated by Django 4.2.7 on 2025-07-27 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CallSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('call_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('call_type', models.CharField(choices=[('audio', 'Audio Only'), ('video', 'Video Call'), ('screen_share', 'Screen Share')], default='video', max_length=20)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('ringing', 'Ringing'), ('active', 'Active'), ('ended', 'Ended'), ('missed', 'Missed')], default='waiting', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('recording_enabled', models.BooleanField(default=False)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_calls', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(through='calls.CallParticipant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CallQualityMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('bandwidth_kbps', models.IntegerField(default=0)),
                ('latency_ms', models.IntegerField(default=0)),
                ('packet_loss_percent', models.FloatField(default=0.0)),
                ('video_quality', models.CharField(default='medium', max_length=20)),
                ('audio_quality', models.CharField(default='medium', max_length=20)),
                ('call_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calls.callsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='callparticipant',
            name='call_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calls.callsession'),
        ),
        migrations.AddField(
            model_name='callparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['started_at'], name='calls_calls_started_6c39c8_idx'),
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['call_type', 'started_at'], name='calls_calls_call_ty_ee5989_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='callparticipant',
            unique_together={('call_session', 'user')},
        ),
    ]
